### ISSUE TITLE
A couple bugs the Chimp&See team noticed

### ISSUE THREAD

**Issue by trouille** [zooniverse/pandora#146]
Message from Chimp&See lead about a couple issues she noticed in their translations:

1) Will the display names of the workflows use the translations we have provided? Currently, there is the option to translate them, and we have, but they always show up in English whenever we view the site in another language. We reference these workflow names elsewhere and we would like to know whether or not to always mention them in English or if we can use the translated names.

2. The links at the top of the project (About, Classify, Talk...) are translated so far for Spanish and Czech, but not for German, and I don't see where those might be translated with the Lab interface. Is this something that is being implemented on Zooniverse's end, and will eventually be done for all languages? 

Just let me know if you need their OS, etc. and I can provide. I'm assuming these bugs are universal, but if they're not, can obtain their info.

**Comment by eatyourgreens** [comment]
Neither of these are related to Pandora so I’m going to close this.

**Comment by yshish** [comment]
@eatyourgreens There's a new text section "workflow description" that we translated in Pandora but when previewing the translations, it keeps appearing in English. 
Is that a bug or something that just won't display translated anytime soon (like the workflow names)?Here's what I mean - the text above the workflow buttons: 

![ysh_Screenshot_2019-07-11_09-23-48](https://user-images.githubusercontent.com/7211888/61030468-b6a62900-a3bd-11e9-9a5a-479f603c7a32.png)

It would really help if it was understandable since the names cannot be translated now.
Thanks.

**Comment by eatyourgreens** [comment]
@yshish @trouille that page (the project home page) is part of PFE, not Pandora. https://github.com/zooniverse/Panoptes-Front-End
